apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: aswines/ticketing-auth
        envFrom:
          - configMapRef:
              name: auth-config
        resources:
          limits:
            memory: "1280Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
  - port: 3001
    targetPort: 3001


