# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: kafka-depl
# spec:
#   selector:
#     matchLabels:
#       app: kafka
#   template:
#     metadata:
#       labels:
#         app: kafka
#     spec:
#       containers:
#       - name: kafka
#         image:  confluentinc/cp-kafka:latest
#         env:
#           - name: KAFKA_BROKER_ID
#             value: '1'
#           - name: KAFKA_ZOOKEEPER_CONNECT
#             value: zookeeper-srv:2181
#           - name: KAFKA_ADVERTISED_LISTENERS
#             value: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:29092
#           - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
#             value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#           - name: KAFKA_INTER_BROKER_LISTENER_NAME
#             value: PLAINTEXT
#           - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
#             value: '1'
#         resources:
#           limits:
#             memory: "128Mi"
#             cpu: "500m"            

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: kafka
# spec:
#   selector:
#     app: profile
#   ports:
#   - name: plaintext-host
#     port: 29092
#     targetPort: 29092
#   - name: plaintext
#     port: 9092
#     targetPort: 9092

