name: auth-test
on:
    pull_request: 
        branches: ['main']
        paths: ["backend/auth/src/**"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              
            - name: install dependencies
              run: cd backend/auth && npm install

            - name: Setting Env
              run: |
                echo "PORT=${{ secrets.PORT }}" > .env
                echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> .env
                echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
            
            - name: Running tests
              run: cd backend/auth && npm run test:ci
              
