name: auth-test

on:
  pull_request:
    branches: ['main']
    paths:
      - 'backend/auth/src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          echo "PORT=${{ secrets.PORT }}" > $GITHUB_WORKSPACE/backend/auth/.env
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> $GITHUB_WORKSPACE/backend/auth/.env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> $GITHUB_WORKSPACE/backend/auth/.env
          
      - name: Install dependencies
        run: cd backend/auth && npm install


      - name: Running tests
        run: cd backend/auth && npm run test:ci
